# example SVD 

In [2]:
import numpy as np

In [4]:
A = np.matrix([[1,2,3,4],[5,6,7,8]])
print(A)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# SVD
U, S, V = np.linalg.svd(A, full_matrices=True)

In [6]:
print(U)

[[-0.37616823 -0.92655138]
 [-0.92655138  0.37616823]]


In [7]:
print(S)

[14.22740741  1.25732984]


In [8]:
print(V)

[[-0.35206169 -0.44362578 -0.53518987 -0.62675396]
 [ 0.75898127  0.3212416  -0.11649807 -0.55423774]
 [-0.40008743  0.25463292  0.69099646 -0.54554195]
 [-0.37407225  0.79697056 -0.47172438  0.04882607]]
